#!/usr/bin/env bash

# This script hijacks the flutter command.
# It prevents the switching of channels, because this needs to be done by downloading a channel from the archive.
# And it prevents doing an upgrade while the active Flutter version points to a versioned directory.

if [[ $1 == "channel" ]]
then
    echo "Switching channels is not allowed when using flutter-version."
    exit 1
elif [[ $1 == "upgrade" ]]
then
    # Make sure we are NOT in a versioned directory, like flutter-3.16.2
    OUTPUT=`flutter-version is-versioned`
    if [[ $OUTPUT == "1" ]]
    then
        echo "Upgrading while in a versioned Flutter directory is not allowed."
        exit 1
    fi
fi

# Get the real flutter path and execute it with the provided arguments.
FLUTTER_CMD_PATH=`flutter-version flutter-path`

if [[ -z "$FLUTTER_CMD_PATH" ]]
then
    echo "The flutter-version command is not found."
    exit 1
fi

eval $FLUTTER_CMD_PATH "$@"
